/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Entidades.Presupuesto;
import Entidades.Familia;
import Negocios.Metodos;
import java.util.ArrayList;

/**
 *
 * @author Veronica Quesada
 */
public class Consulta4 extends javax.swing.JFrame {
Metodos procesos = new Metodos();
    /**
     * Creates new form Consulta4
     */
    public Consulta4() {
        initComponents();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consulta4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consulta4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consulta4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consulta4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consulta4().setVisible(true);
            }
        });
    }
public void consulCuatro(){                                                 //this method shows how many families use more than 10% of their income for self-fulfillment activities 
        ArrayList<Presupuesto> usuarios = procesos.extraerIngresoFamilia(); 
        ArrayList<Presupuesto> usuario = procesos.extraerEgresoFamilia();
         ArrayList<Familia> fam = procesos.mostrarReporte();
         
         int Ingreso=0;
         int montoIngreso=0;
         int porcenIngreso=0;
         int montoEgreso=0;
         int cantidad =0;
         int contFamilias=0;
         float once= (float) 0.11;
         cantidad = procesos.mostrarReporte().size();       //Get a list with all families that exist
         while (cantidad >0){   
         for (Familia temps : fam) {
            for (Presupuesto temp : usuarios) {
                Ingreso= temp.getMonto();
                porcenIngreso= (int) (Ingreso*once ) ;
                if(temps.getApellido().equals(temp.getTipo())){
                    for(Presupuesto tem: usuario){
                        montoEgreso= tem.getMonto();
                        //Cargar Cambios de Fer para obtener Egreso por Autorealización 
                        contFamilias++;
                        
                        
                        
                        
                    }
                    
                    
                    
                    
                 }   
                    
                }
            }   
            }
                
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
}