/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Entidades.Presupuesto;
import Negocios.Metodos;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author ma210
 */
public class ConsultasGeneral extends javax.swing.JFrame {
       Metodos procesos = new Metodos();
          int cedulas;
       

    /**
     * Creates new form ConsultasGeneral
     */
    public ConsultasGeneral(java.awt.Frame parent, boolean modal) {
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnConsulta1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnConsulta1.setText("Consulta 1");

        jButton1.setText("Consulta 2");

        jButton2.setText("Consulta 3");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Consulta 4 ");

        jButton4.setText("Consulta 5");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Consultas generales");

        jButton5.setText("Consulta 6");

        jButton6.setText("Consulta 7");

        jButton7.setText("Consulta 8");

        jButton8.setText("Consulta 9");

        jButton9.setText("Consulta 10");

        jButton10.setText("Salir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BtnConsulta1)
                                    .addComponent(jButton1)
                                    .addComponent(jButton2)
                                    .addComponent(jButton3)
                                    .addComponent(jButton4))
                                .addGap(159, 159, 159)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton7)
                                    .addComponent(jButton6)
                                    .addComponent(jButton5)
                                    .addComponent(jButton8)
                                    .addComponent(jButton9)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jButton10)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnConsulta1)
                    .addComponent(jButton5))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jButton6)))
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton7))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton3))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton10)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
      
        mostrar();
            
    }//GEN-LAST:event_jButton4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultasGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultasGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultasGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultasGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
             public void run() {
                RegistrarFamilia dialog = new RegistrarFamilia(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });

    }
    
    public void mostrar(){
          int preescolar = 0;
          int primariaCompleta = 0;
          int primariaIncompleta = 0;
          int secundariaCompleta = 0;
          int secundariaIncompleta =0;
          int universidadCompleta = 0;
          int universidadIncompleta = 0;
          int noAplica = 0;
          
             ArrayList<Presupuesto> usuarios = procesos.mostrarReporte5();
            for (Presupuesto temp : usuarios) {
                if(temp.getTipo().equals("Preescolar")){
                     preescolar += temp.getMonto();
                }else if (temp.getTipo().equals("Primaria Completa")){
                    primariaCompleta += temp.getMonto();   
                }else if (temp.getTipo().equals("Primaria Incompleta")){
                    primariaIncompleta += temp.getMonto();   
            }else if (temp.getTipo().equals("Secundaria Completa")){
                    secundariaCompleta += temp.getMonto();
            }else if (temp.getTipo().equals("Secundaria Incompleta")){
                    secundariaIncompleta += temp.getMonto();
            }else if (temp.getTipo().equals("Universidad Completa")){
                     universidadCompleta += temp.getMonto();
            }else if (temp.getTipo().equals("Universidad Incompleta")){
                    universidadIncompleta += temp.getMonto();
            }else {
                 noAplica += temp.getMonto();
            }
    }
            if(preescolar > primariaCompleta && preescolar > primariaCompleta && preescolar > primariaIncompleta
                   && preescolar > secundariaCompleta && preescolar > secundariaIncompleta && preescolar > universidadCompleta
                    && preescolar > universidadIncompleta && preescolar > noAplica){
                JOptionPane.showMessageDialog(rootPane,"Ahorro más el grado de escolaridad de preescolar");
            } else if(primariaCompleta > preescolar && primariaCompleta > primariaIncompleta
                   && primariaCompleta > secundariaCompleta && primariaCompleta > secundariaIncompleta && primariaCompleta > universidadCompleta
                    && primariaCompleta > universidadIncompleta && primariaCompleta > noAplica){
                JOptionPane.showMessageDialog(rootPane,"Ahorro más el grado de escolaridad de preescolar");
            } else if (primariaIncompleta > preescolar && primariaIncompleta > primariaCompleta
                   && primariaIncompleta > secundariaCompleta && primariaIncompleta > secundariaIncompleta && primariaIncompleta > universidadCompleta
                    && primariaIncompleta > universidadIncompleta && primariaIncompleta > noAplica){
                 JOptionPane.showMessageDialog(rootPane,"Ahorro más el grado de escolaridad de primeria Incompleta");
            }else if (secundariaCompleta > preescolar && secundariaCompleta > primariaCompleta && secundariaCompleta > primariaIncompleta
                   && secundariaCompleta >  secundariaIncompleta && secundariaCompleta > universidadCompleta
                    && secundariaCompleta > universidadIncompleta && secundariaCompleta > noAplica){
                 JOptionPane.showMessageDialog(rootPane,"Ahorro más el grado de escolaridad de Secundaria Incompleta");
            }else if(secundariaIncompleta > preescolar && secundariaIncompleta > primariaCompleta &&  secundariaIncompleta > primariaIncompleta
                    &&  secundariaIncompleta > secundariaCompleta &&  secundariaIncompleta > universidadCompleta && 
                    secundariaIncompleta > universidadIncompleta && secundariaIncompleta > noAplica){
            JOptionPane.showMessageDialog(rootPane,"Ahorro más el grado de escolaridad de Secundaria Completa");
    }else if(universidadIncompleta > preescolar && universidadIncompleta > primariaCompleta &&  universidadIncompleta > primariaIncompleta
                    &&  universidadIncompleta > secundariaCompleta &&  universidadIncompleta > universidadCompleta && 
                    universidadIncompleta > secundariaIncompleta && universidadIncompleta > noAplica){
            JOptionPane.showMessageDialog(rootPane,"Ahorro más el grado de escolaridad de Universidad Incompleta");
    }else if(universidadCompleta > preescolar && universidadCompleta > primariaCompleta &&  universidadCompleta > primariaIncompleta
                    &&  universidadCompleta > secundariaCompleta &&  universidadCompleta > universidadIncompleta && 
                    universidadCompleta > secundariaIncompleta && universidadCompleta > noAplica){
            JOptionPane.showMessageDialog(rootPane,"Ahorro más el grado de escolaridad de Universidad Completa");
    }else{
         JOptionPane.showMessageDialog(rootPane,"Ahorro más el grado de escolaridad No aplica ");
    }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnConsulta1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
