/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Entidades.Persona;
import Entidades.Presupuesto;
import Negocios.Metodos;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author ma210
 */
public class IngresarAhorro extends javax.swing.JFrame {
    
    ArrayList<Presupuesto> usuarios;  
    Metodos procesos = new Metodos();
       Persona personas = new Persona();
    int cedulas;
      
    /**
     * Creates new form IngresarAhorro
     */
    public IngresarAhorro( int cedula) {
        initComponents();
        cedulas = cedula;
        calcularRestante();
    }

    private IngresarAhorro() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtRestante = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jlTexto = new javax.swing.JLabel();
        jlAhorro = new javax.swing.JLabel();
        txtAhorro = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jlTitulo = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Restante");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Ingresar Ahorro");

        jlAhorro.setText("Ahorro:");

        btnGuardar.setText("Guardar Ahorro");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jlTitulo.setText("Monto para ahorrar");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlAhorro)
                                .addGap(28, 28, 28)
                                .addComponent(txtAhorro, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(txtRestante, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jlTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jlTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(btnGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalir)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtRestante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jlTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlAhorro)
                    .addComponent(txtAhorro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnSalir))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
      
       int monto = Integer.parseInt(txtAhorro.getText());
       int ahorro = 0;
       int calculo = calcularRestante();
       
       
       if(monto> calculo && monto > 0){
           JOptionPane.showMessageDialog(rootPane,"El monto excede el limite");
       }else{
           
           
           int id  = cedulas;
           Persona p = new Persona(id);
           Presupuesto ahorros = new Presupuesto(p, monto);
        Presupuesto usu = new Presupuesto(p);
        usuarios = procesos.extraerEgreso(usu);
        
        
        for (Presupuesto temp : usuarios) {
               ahorro = temp.getMonto();
       }
        if (ahorro == 0){
              procesos.actualizarAhorro(ahorros);
                dispose();
            volverInicio();
        }else{
               procesos.guardarAhorro(ahorros);
                 dispose();
            volverInicio();
        }
       
         
       }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
       volverInicio();
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresarAhorro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresarAhorro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresarAhorro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresarAhorro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresarAhorro().setVisible(true);
            }
        });
    }
    
    public int ingresoPorPersona(){
        int ingreso = 0;
        int id = cedulas;
           Persona p = new Persona(id);
           Presupuesto usu = new Presupuesto(p);
        usuarios = procesos.extraerIngreso(usu);         
        
        
        for (Presupuesto temp : usuarios) {
               ingreso = temp.getMonto();
       }
        return ingreso;
        
    }
    

    
     public int EgresoPorPersona(){
        int egreso = 0;
        int id = cedulas;
         Persona p = new Persona(id);
           Presupuesto usu = new Presupuesto(p);
        usuarios = procesos.extraerEgreso(usu);
        
        
        for (Presupuesto temp : usuarios) {
               egreso = temp.getMonto();
       }
        return egreso;
        
    }

     public int calcularRestante(){
         int egresos = EgresoPorPersona();
         int ingreso = ingresoPorPersona();
         
         int restante = ingreso - egresos;
         
         if(restante <= 0){
             txtRestante.enable(false);
             txtRestante.setText(String.valueOf(restante));
             jlAhorro.setVisible(false);
             txtAhorro.setVisible(false);
             jlTitulo.setVisible(false);
             btnGuardar.setVisible(false);
             jlTexto.setText("Monto insuficiente para ahorrar");
         }else{
                  txtRestante.enable(false);
                  txtRestante.setText(String.valueOf(restante));
             
         }
         return restante;
       
        
     }
   public void volverInicio(){
         Inicio ventana = new Inicio(this,true);
        ventana.pack();
        setVisible(false);
        ventana.setVisible(true);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jlAhorro;
    private javax.swing.JLabel jlTexto;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JTextField txtAhorro;
    private javax.swing.JTextField txtRestante;
    // End of variables declaration//GEN-END:variables
}
